# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ClosureProtocol' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ClosureProtocol

  target 'ClosureProtocolTests' do
    inherit! :search_paths
    # Pods for testing
  end
pod 'Alamofire'
pod 'SDWebImage', '5.12.6'
  target 'ClosureProtocolUITests' do
    # Pods for testing
  end

end
